### ISSUE TITLE
The documentation in the readme is linked to Page Not Found

### ISSUE THREAD

**Issue by rafaela-amorim** [py-why/pywhy-stats#9]
**Is your feature request related to a problem? Please describe.**
Hey I just wanted to let you know the links for the documentation are broken in the readme. Also the "installation page" link

**Describe the solution you'd like**
The documentation if it is done, or some kind of flag like WIP if it is undone or it doesn't exist

**Comment by adam2392** [comment]
Hi @rafaela-amorim the package is/was still in development.

The latest commit has the documentation rendered now with each push to main: https://www.pywhy.org/pywhy-stats/dev/index.html
